runtime: python39
instance_class: F1

env_variables:
  FLASK_APP: main.py
  FLASK_ENV: production

entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: auto