"""Increase isbn length to 20

Revision ID: b6e602ed21d8
Revises: 
Create Date: 2025-04-05 11:49:18.474043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e602ed21d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to raw SQL ###
    # Use raw SQL for potentially more reliable execution in Cloud Run environment
    op.execute('ALTER TABLE book ALTER COLUMN isbn TYPE VARCHAR(20);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted to raw SQL ###
    # Use raw SQL for potentially more reliable execution in Cloud Run environment
    op.execute('ALTER TABLE book ALTER COLUMN isbn TYPE VARCHAR(13);')
    # ### end Alembic commands ###
